# Generated by Django 4.1.1 on 2023-02-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True)),
                ('humid', models.FloatField(null=True)),
                ('status_fan', models.BooleanField(null=True)),
                ('status_lamp', models.BooleanField(null=True)),
                ('status_water', models.BooleanField(null=True)),
                ('adc', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'iot',
            },
        ),
    ]
